### ISSUE TITLE
tag detection and depup rule not adjust

### ISSUE THREAD

**Issue by tsuyoshicho** [haya14busa/action-depup#10]
Hi

I tried using to [tsuyoshicho/action-redpen](https://github.com/tsuyoshicho/action-redpen)

And I have two problems, these same root causes I think.

## Problems

1st try.

1. depup fill full tag name
https://github.com/tsuyoshicho/action-redpen/runs/402637486
```
Current REDPEN_VERSION=1.10.4
...
Latest REDPEN_VERSION=redpen-1.10.4
```

Docker file change REDPEN_VERSION is full tag name string work fine
and 2nd try.

2. depup not detect full tag name
https://github.com/tsuyoshicho/action-redpen/runs/404744311
```
cannot parse REDPEN_VERSION like full tag name
```

https://github.com/tsuyoshicho/action-redpen/blob/c583ea0235176c94d24c4777e2dc40bd59caa251/Dockerfile
```Dockerfile
FROM openjdk:12-alpine

ENV REDPEN_VERSION=redpen-1.10.3
...
```

ENV detecting/parsing rule are `*.*.*` (semver)
But fill full tag (i.e. redpen-1.10.4)

## Suggestions

What about the fix methods below?

1. ENV detect point (redpen-*1.10.4*) replace.
2. fill re-match semver string only ( *REDPEN_VERSION=1.10.4* )

see https://github.com/redpen-cc/redpen/releases

**Comment by haya14busa** [comment]
Pull request is welcome.
I cannot prioritize it to work on it by myself as I haven't heard such kind of tag other than redpen.

**Comment by tsuyoshicho** [comment]
OK, I understood current this acton's software specifications and work target.

**Comment by haya14busa** [comment]
On second thought, it's actually easy to support it. Fixed with implementation (2)

**Comment by tsuyoshicho** [comment]
I retry it.
